### ISSUE TITLE
java.lang.UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile

### ISSUE THREAD

**Issue by wallaby-pouch** [dboissier/mongo4idea#101]
Hi,
I'm the author of the BashSupport plugin. I've received the following stacktrace, which probably is related to your plugin.

org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
java.lang.UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
	at com.intellij.openapi.vfs.VirtualFile.getModificationStamp(VirtualFile.java:639)
	at com.intellij.psi.impl.file.PsiBinaryFileImpl.<init>(PsiBinaryFileImpl.java:52)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:267)
	at com.intellij.psi.SingleRootFileViewProvider.b(SingleRootFileViewProvider.java:248)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:157)
	at com.intellij.psi.SingleRootFileViewProvider.getPsi(SingleRootFileViewProvider.java:141)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:366)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:184)
	at com.intellij.ide.impl.dataRules.PsiFileRule.getData(PsiFileRule.java:39)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:83)
	at com.intellij.ide.impl.DataManagerImpl.access$000(DataManagerImpl.java:50)
	at com.intellij.ide.impl.DataManagerImpl$1.getData(DataManagerImpl.java:86)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:81)
	at com.intellij.ide.impl.dataRules.VirtualFileArrayRule.getData(VirtualFileArrayRule.java:90)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:83)
	at com.intellij.ide.impl.DataManagerImpl.access$000(DataManagerImpl.java:50)
	at com.intellij.ide.impl.DataManagerImpl$1.getData(DataManagerImpl.java:86)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:81)
	at com.intellij.ide.impl.dataRules.ModuleRule.getData(ModuleRule.java:55)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:83)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:64)
	at com.intellij.ide.impl.DataManagerImpl.access$300(DataManagerImpl.java:50)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.a(DataManagerImpl.java:366)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:343)
	at com.ansorgit.plugins.bash.actions.NewBashActionBase.update(NewBashActionBase.java:74)
	at com.ansorgit.plugins.bash.actions.NewBashFileAction.update(NewBashFileAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:265)
	at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:74)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:45)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:39)
	at com.intellij.ide.actions.NewElementAction.update(NewElementAction.java:98)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.g(ActionMenu.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1037)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1117)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1186)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:209)
	at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
	at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:450)
	at java.awt.Component.processMouseEvent(Component.java:6522)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
Hi,

Which version do you have? This bug (#97) has been fixed in the lastest 0.7.0 version.

**Comment by wallaby-pouch** [comment]
I don't know the plugin version. If you fixed the exception in 0.7.0 then just close this issue.
Thanks!
-- 
<>< Re: deemed!
