### ISSUE TITLE
Plugin crashes if cannot connect to server

### ISSUE THREAD

**Issue by Grzegorzsa** [dboissier/mongo4idea#108]
I manually switch on local Mongo server when I work on certain projects. When I work on other projects and keep my Mongo server down plugin crashes.

plugin version 0.7
Windows 7 64, webstorm 8.0.5

**Comment by dboissier** [comment]
Hi,

Is Mongo server for "others projects" is local or remote?
Do you have any stacktrace that could help on investigation?

Thanks

**Comment by Grzegorzsa** [comment]
"other project" means PHP-MySQL. Mongo plugin is connected to local server only. Error shows from time to time asking me to disable the plugin. I cannot find any stack trace. When I see this error again I will try to investigate it and get this stack trace if there is any.

**Comment by Grzegorzsa** [comment]
Error when collecting Mongo databases: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.BaseCluster.getDescription(BaseCluster.java:128)
	at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:394)
	at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:571)
	at com.mongodb.DBTCPConnector.getReplicaSetStatus(DBTCPConnector.java:362)
	at com.mongodb.Mongo.getReplicaSetStatus(Mongo.java:446)
	at com.mongodb.DB.getCommandReadPreference(DB.java:82)
	at com.mongodb.DB.command(DB.java:317)
	at com.mongodb.DB.command(DB.java:299)
	at com.mongodb.DB.command(DB.java:374)
	at com.mongodb.Mongo.getDatabaseNames(Mongo.java:373)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadDatabaseCollections(MongoManager.java:113)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadServer(MongoManager.java:93)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadServers(MongoManager.java:85)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.run(MongoExplorerPanel.java:132)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by dboissier** [comment]
perhaps this bug is similar to #114

**Comment by Grzegorzsa** [comment]
Perhaps it is in some way. I do not use any authentication locally though. Plubin crashes when my local mongo server is down.

**Comment by dboissier** [comment]
Ok.

I understand better the situation. I will improve the connection exception handling.

**Comment by dboissier** [comment]
Hi,

do you still have the bug in the latest 0.7.2 version?

**Comment by Grzegorzsa** [comment]
I connot install the plugin. I didn't update the Webstorm to the last version (I use 8.0.5) .  I've got a message: "Plugin Mongo Plugin is incompatibile with current installation".

**Comment by dboissier** [comment]
Hi,

What is the status of this issue?

**Comment by Grzegorzsa** [comment]
I didn't upgrade my Webstorm and new version of plugin doesn't work for me any more. I am closing it as I'm unable to check whether it is working correctly or not.
