### ISSUE TITLE
Pycharm 5.0 NoClassDefFoundError

### ISSUE THREAD

**Issue by arj-196** [dboissier/mongo4idea#122]
Mongo explorer works, but mongo shell won't open giving this error: 

	com/intellij/execution/runners/ConsoleExecuteActionHandler
	java.lang.NoClassDefFoundError: com/intellij/execution/runners/ConsoleExecuteActionHandler
		at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.runShell(MongoConsoleAction.java:67)
		at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.actionPerformed(MongoConsoleAction.java:63)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
		at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
		at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
		at java.awt.Component.processEvent(Component.java:6290)
		at java.awt.Container.processEvent(Container.java:2234)
		at java.awt.Component.dispatchEventImpl(Component.java:4881)
		at java.awt.Container.dispatchEventImpl(Container.java:2292)
		at java.awt.Component.dispatchEvent(Component.java:4703)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
		at java.awt.Container.dispatchEventImpl(Container.java:2278)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4703)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	Caused by: java.lang.ClassNotFoundException: com.intellij.execution.runners.ConsoleExecuteActionHandler PluginClassLoader[Mongo Plugin, 0.7.0]
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 38 more

Direct download from pycharm gives me version 0.7.0, that gives the error above. 

I couldn't fin 0.7.1, but 0.7.2 is available here: https://plugins.jetbrains.com/plugin/7141?pr=idea, but can't install, says it is not compatible.

**Comment by dboissier** [comment]
Hi,

Pycharm 5.0 is based on the latest plateform version (such as IntelliJ 15 for instance). I will put a snapshot version on the next Thursday that is compiled with this version. Then I will ask you to test it and confirm it works.

Thanks for your patience

**Comment by dboissier** [comment]
Hi,

please test the following [SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.3-SNAPSHOT-distribution.zip) and tell me if it works on Idea 15.

Thanks.

**Comment by Den-dp** [comment]
@dboissier this one works for me

**Comment by arj-196** [comment]
@dboissier  worked for me ! Thank you
