### ISSUE TITLE
Plugin Error when clicking 'Mongo Settings'

### ISSUE THREAD

**Issue by tanyapowell** [dboissier/mongo4idea#139]
Trying to set up my remote connection via the settings in the plugin in IntelliJ 15. When I click on __Mongo Settings__ I'm taken to the plugin preferences. When clicking on either __expand al_l_ or __collapse all__ I get `NullPointerException: null` 

Have uninstalled and reinstalled 3x with no luck

**Comment by dboissier** [comment]
Hi,

Do you have any stacktrace printed in the Event log panel? It would be convenient to find the root cause.

Cheers

**Comment by tanyapowell** [comment]
The only stacktrace I get is `NullPointerException: null` when clicking on either expand all or collapse all

**Comment by jtallen** [comment]
I am having a similar issues with clicking on expand all or collapse all. Except in my case, when I click on the settings button, it takes me to `Preferences > Languages and Frameworks`... the overall Intellij settings, not something related to Mongo.

I also received the `NullPointerException: null` error when trying to expand all/collapse all, here is the stacktrace:
```
null
java.lang.NullPointerException
	at com.intellij.util.ui.tree.TreeUtil.collapseAll(TreeUtil.java:737)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel.collapseAll(MongoExplorerPanel.java:281)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel.access$500(MongoExplorerPanel.java:58)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.collapseAll(MongoExplorerPanel.java:204)
	at com.intellij.ide.actions.TreeCollapseAllActionBase.actionPerformed(TreeCollapseAllActionBase.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
