### ISSUE TITLE
Error running a script

### ISSUE THREAD

**Issue by jonatasrenan** [dboissier/mongo4idea#155]
OS X 10.11.5 (15F34)
WebStorm 2016.1.3
Mongo4idea 0.8

when I running a .js script into webstorm using standard mongo configuration: 

<img width="521" alt="screen shot 2016-06-23 at 2 54 50 pm" src="https://cloud.githubusercontent.com/assets/5423293/16314043/7881d38c-3952-11e6-8b76-d2c77bdcec54.png">

I received the following error:

<img width="399" alt="screen shot 2016-06-23 at 2 56 38 pm" src="https://cloud.githubusercontent.com/assets/5423293/16314135/d6dbb5a6-3952-11e6-9abd-2535c2264e1d.png">

If "Continue anyway" I get the following error:
2:48:34 PM NullPointerException: null

null
java.lang.NullPointerException
	at org.codinjutsu.tools.mongo.utils.MongoUtils.buildMongoUrl(MongoUtils.java:50)
	at org.codinjutsu.tools.mongo.runner.MongoCommandLineState.generateCommandLine(MongoCommandLineState.java:60)
	at org.codinjutsu.tools.mongo.runner.MongoCommandLineState.startProcess(MongoCommandLineState.java:46)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:291)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:432)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:121)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:116)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:67)
	at com.intellij.execution.impl.ExecutionManagerImpl$7.run(ExecutionManagerImpl.java:516)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
bug! Will llok at this.

Thanks for reporting it :)

**Comment by korsmakolnikov** [comment]
Same probleme here. 
I see when I put working dir in configuration (project root), actually starts but seems that cannot find the script file. 

here is the console output:
`/usr/local/bin/mongo localhost:27017/gestoProd ""
MongoDB shell version v3.4.2
connecting to: mongodb://localhost:27017/gestoProd
MongoDB server version: 3.4.2
2017-05-26T11:19:08.987+0200 E -        [main] file [] doesn't exist
failed to load: 

Process finished with exit code 253`
