### ISSUE TITLE
source can not be null

### ISSUE THREAD

**Issue by OrangeDog** [dboissier/mongo4idea#156]
IntelliJ IDEA 2016.1.3
Plugin version 0.7.6

I've filled in Server url, Username, Password and Auth. database fields.
Error on connection:

```
java.lang.IllegalArgumentException: source can not be null
    at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
    at com.mongodb.MongoCredential.<init>(MongoCredential.java:233)
    at com.mongodb.MongoCredential.createPlainCredential(MongoCredential.java:174)
    at org.codinjutsu.tools.mongo.logic.MongoManager.getMongoCredential(MongoManager.java:309)
    at org.codinjutsu.tools.mongo.logic.MongoManager.createMongoClient(MongoManager.java:301)
    at org.codinjutsu.tools.mongo.logic.MongoManager.loadDatabaseCollections(MongoManager.java:92)
    at org.codinjutsu.tools.mongo.logic.MongoManager.loadServer(MongoManager.java:81)
    at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.run(MongoExplorerPanel.java:153)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Connecting to a different server, without authentication, works correctly.

**Comment by dboissier** [comment]
HI,

A build is available on the home page and fix it (#153) . Tell me whether it works. I would release it officially by the end of this week.

Sorry for the inconvenience
