### ISSUE TITLE
CodecConfigurationException on query collection with DBRef

### ISSUE THREAD

**Issue by RomanIsko** [dboissier/mongo4idea#173]
Environment:
Ubuntu 16.04
IDEA 2016.2.5
Java 1.8.0_111

Steps:
- prepare DB with this query
```
db.example.insert({
  "_id" : ObjectId("5126bbf64aed4daf9e2ab771"),
  "creator" : {
                  "$ref" : "creators",
                  "$id" : ObjectId("5126bc054aed4daf9e2ab772"),
                  "$db" : "users"
               }
})
```
- open IDEA
- Invoke 'View collection content' from context menu
- check Event log

Actual: Data isn't shown for user because there is CodecConfigurationException in Event log
```
Can't find a codec for class com.mongodb.DBRef.
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com.mongodb.DBRef.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:174)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
	at org.bson.Document.toJson(Document.java:294)
	at org.bson.Document.toJson(Document.java:268)
	at org.bson.Document.toJson(Document.java:255)
	at org.codinjutsu.tools.mongo.view.nodedescriptor.MongoValueDescriptor$MongoDocumentValueDescriptor.toString(MongoValueDescriptor.java:175)
	at javax.swing.tree.DefaultMutableTreeNode.toString(DefaultMutableTreeNode.java:1244)
	at javax.swing.JTree.convertValueToText(JTree.java:1596)
	at javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent(DefaultTreeCellRenderer.java:428)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree$1.getTreeCellRendererComponent(TreeTableTree.java:122)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1496)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:109)
	at javax.swing.plaf.basic.BasicTreeUI.setModel(BasicTreeUI.java:412)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3414)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at javax.swing.JTree.setModel(JTree.java:882)
	at javax.swing.JTree.<init>(JTree.java:670)
	at com.intellij.ui.treeStructure.Tree.<init>(Tree.java:68)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree.<init>(TreeTableTree.java:43)
	at com.intellij.ui.treeStructure.treetable.TreeTable.setModel(TreeTable.java:65)
	at com.intellij.ui.treeStructure.treetable.TreeTable.<init>(TreeTable.java:57)
	at org.codinjutsu.tools.mongo.view.JsonTreeTableView.<init>(JsonTreeTableView.java:77)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.updateResultTreeTable(MongoResultPanel.java:119)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.updateResultView(MongoResultPanel.java:112)
	at org.codinjutsu.tools.mongo.view.MongoPanel$4$2.run(MongoPanel.java:222)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Expected: Content is shown for user without exception.

**Comment by dboissier** [comment]
Hi,

I found a [fix](http://stackoverflow.com/questions/31237849/cant-find-a-codec-for-class-com-mongodb-basicdbobject-error-in-java-using-mondo#35856263).

I will patch it and provide a snapshot build asap.

Thanks,

**Comment by dboissier** [comment]
Hi,

This issue goes beyond I have expected. This is related to the #133. I updated the code to handle the DBRef object. I will publish a snapshot to let you confirm that its fixing and then I will work on navigation between reference.

**Comment by dboissier** [comment]
Hi,

A SNAPSHOT build is [available](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.10.0-SNAPSHOT-idea2016-distribution.zip). Please download & install it. Tell me whether the issue is fixed or not.

**Comment by RomanIsko** [comment]
Hi, @dboissier 
I've just tried to install SNAPSHOT build on IDEA 2016.2.5 and installation fails with 
*Plugin 'Mongo Plugin' is incompatible with this installation*
![selection_240](https://cloud.githubusercontent.com/assets/4456572/20521616/b58a2926-b0b4-11e6-9a40-52b6154d8c2a.png)

**Comment by dboissier** [comment]
I fixed the compatibility version. Please download it again and sorry for the inconvenience.

**Comment by RomanIsko** [comment]
@dboissier Thank for the fix. I can verify that SNAPSHOT plugin works with IDEA 2016.2 and 2016.3

**Comment by dboissier** [comment]
Hi,

I uploaded a new SNAPSHOT. You can view the referenced document in a Dialog. Selecting it in the view, right-click on View Reference. As alternative you can use the shortcut ⌘ + B.

Please tell me if it is fine or some improvement would be needed.

Thanks.

**Comment by RomanIsko** [comment]
Hi @dboissier 
I'm getting this exception on 'View reference':

name can not be null
java.lang.IllegalArgumentException: name can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
	at com.mongodb.MongoDatabaseImpl.<init>(MongoDatabaseImpl.java:48)
	at com.mongodb.MongoClient.getDatabase(MongoClient.java:354)
	at org.codinjutsu.tools.mongo.logic.MongoManager$4.run(MongoManager.java:134)
	at org.codinjutsu.tools.mongo.logic.MongoManager$4.run(MongoManager.java:130)
	at org.codinjutsu.tools.mongo.logic.MongoManager.execute(MongoManager.java:167)
	at org.codinjutsu.tools.mongo.logic.MongoManager.findMongoDocument(MongoManager.java:142)
	at org.codinjutsu.tools.mongo.view.MongoPanel$1.getReferenceDocument(MongoPanel.java:86)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.getReferencedDocument(MongoResultPanel.java:319)
	at org.codinjutsu.tools.mongo.view.action.GoToMongoDocumentAction.actionPerformed(GoToMongoDocumentAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:315)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
Hi,

The mongo driver says the database name `users`  is incorrect or null. How is structured your DBRef?

**Comment by RomanIsko** [comment]
Actually, I tested with other DB. 
Here is the structure of my DB:
![selection_244](https://cloud.githubusercontent.com/assets/4456572/20604156/a89d7532-b26d-11e6-857a-fe2ac72940a5.png)

**Comment by dboissier** [comment]
Your `$db` value is `null`. This is why the mongo driver is unable to retrieve the document. Do I have to assume that in this case it is the same database?

**Comment by RomanIsko** [comment]
Yes. If `$db` is null then the same database is used for reference

**Comment by dboissier** [comment]
ok. I will fix it right now. A build should be available in a couple of minutes

**Comment by dboissier** [comment]
SNAPSHOT updated

**Comment by RomanIsko** [comment]
@dboissier thanks for the update, but I still have the same exception

name can not be null
java.lang.IllegalArgumentException: name can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
	at com.mongodb.MongoDatabaseImpl.<init>(MongoDatabaseImpl.java:48)
	at com.mongodb.MongoClient.getDatabase(MongoClient.java:354)
	at org.codinjutsu.tools.mongo.logic.MongoManager$4.run(MongoManager.java:134)
	at org.codinjutsu.tools.mongo.logic.MongoManager$4.run(MongoManager.java:130)
	at org.codinjutsu.tools.mongo.logic.MongoManager.execute(MongoManager.java:167)
	at org.codinjutsu.tools.mongo.logic.MongoManager.findMongoDocument(MongoManager.java:142)
	at org.codinjutsu.tools.mongo.view.MongoPanel$1.getReferenceDocument(MongoPanel.java:86)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.getReferencedDocument(MongoResultPanel.java:319)
	at org.codinjutsu.tools.mongo.view.action.GoToMongoDocumentAction.actionPerformed(GoToMongoDocumentAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:315)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
Hi,

I tried to insert a DBRef with $db=null and I have the following message:
```
The DBRef $db field must be a String, not a NULL
```

So I am not sure to understand what to do because Mongo wants all fields to be set.

**Comment by RomanIsko** [comment]
Thanks for the update. Now I don't have any exception. Reference is shown.

BTW, we use Spring Data MongoDB in our project.
