### ISSUE TITLE
Can't find a codec for class com.mongodb.DBRef.

### ISSUE THREAD

**Issue by tonsV2** [dboissier/mongo4idea#180]
Happens when I click a specific collection in my db. Others work just fine. Please let me know if I should supply more information.

Can't find a codec for class com.mongodb.DBRef.
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com.mongodb.DBRef.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:174)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:197)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:170)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
	at org.bson.Document.toJson(Document.java:294)
	at org.bson.Document.toJson(Document.java:268)
	at org.bson.Document.toJson(Document.java:255)
	at org.codinjutsu.tools.mongo.view.nodedescriptor.MongoValueDescriptor$MongoDocumentValueDescriptor.toString(MongoValueDescriptor.java:175)
	at javax.swing.tree.DefaultMutableTreeNode.toString(DefaultMutableTreeNode.java:1244)
	at javax.swing.JTree.convertValueToText(JTree.java:1596)
	at javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent(DefaultTreeCellRenderer.java:428)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree$1.getTreeCellRendererComponent(TreeTableTree.java:122)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1496)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:109)
	at javax.swing.plaf.basic.BasicTreeUI.setModel(BasicTreeUI.java:412)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3414)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at javax.swing.JTree.setModel(JTree.java:882)
	at javax.swing.JTree.<init>(JTree.java:670)
	at com.intellij.ui.treeStructure.Tree.<init>(Tree.java:68)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree.<init>(TreeTableTree.java:43)
	at com.intellij.ui.treeStructure.treetable.TreeTable.setModel(TreeTable.java:65)
	at com.intellij.ui.treeStructure.treetable.TreeTable.<init>(TreeTable.java:57)
	at org.codinjutsu.tools.mongo.view.JsonTreeTableView.<init>(JsonTreeTableView.java:77)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.updateResultTreeTable(MongoResultPanel.java:119)
	at org.codinjutsu.tools.mongo.view.MongoResultPanel.updateResultView(MongoResultPanel.java:112)
	at org.codinjutsu.tools.mongo.view.MongoPanel$4$2.run(MongoPanel.java:222)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
Hi,

this issue has been fixed in the latest 0.10.X (see #173). Please update the plugin and tell me whether it works on your IDE.

Thanks

**Comment by tonsV2** [comment]
My bad, not sure why intellij didn't asked me to update the plugin. Works just fine after I updated.

**Comment by dboissier** [comment]
Hi,

I need some testers on the DBRef navigation. 

Basically, when you select a DBRef node, use the shortcut `CTRL+B`or `Cmd+B` (right-click to) and the panel will open the concerned referenced document. A `back` button, will appear on the top tool bar so you will be able to go back to the original document.

This feature is experimental. Please feel free to suggest improvements or raise issue.

Thanks.

**Comment by tonsV2** [comment]
Hi,

I just tested and it works just fine. The back button appears and it works.

Thanks for creating and open sourcing this plugin.
