### ISSUE TITLE
Error while trying to delete database

### ISSUE THREAD

**Issue by sylvainbx** [dboissier/mongo4idea#181]
**Steps to reproduce**
 Select a database in the tree, press the delete key on the keyboard.

**Resulting behavior**
The database is not deleted as expected and an error occurred.

**Error stacktrace**
```java
null
java.lang.NullPointerException
	at org.codinjutsu.tools.mongo.view.action.DropCollectionAction.actionPerformed(DropCollectionAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Other details**
If right clicking on the database, then selecting `Drop database`, the error does not occurs and the database is correctly dropped.

**Comment by dboissier** [comment]
Hi,

Thanks for reporting this issue.

**Comment by steinsag** [comment]
I can confirm this bug in latest IntelliJ 2017.3 and plugin version 0.10.2016.

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)

**Comment by sylvainbx** [comment]
Hi, I've just tried your snapshot and I can confirm that the error no longer occurs when pressing the DEL key. However, the prompt for database deletion is not triggered neither.
