### ISSUE TITLE
Dont work plugin Mongo for PhpStorm

### ISSUE THREAD

**Issue by muleronko** [dboissier/mongo4idea#204]
After installation i have next text error:

null
java.lang.NullPointerException
	at org.codinjutsu.tools.mongo.logic.ssh.SshConnection.createSshSession(SshConnection.java:65)
	at org.codinjutsu.tools.mongo.logic.ssh.SshConnection.<init>(SshConnection.java:53)
	at org.codinjutsu.tools.mongo.logic.ssh.SshConnection.create(SshConnection.java:37)
	at org.codinjutsu.tools.mongo.logic.MongoManager.executeTask(MongoManager.java:160)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadDatabaseCollections(MongoManager.java:106)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadServer(MongoManager.java:79)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.run(MongoExplorerPanel.java:160)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dboissier** [comment]
Hi,

which version of PhpStorm do you use?

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)
