### ISSUE TITLE
org.bson.BsonInvalidOperationException: Document does not contain key ns

### ISSUE THREAD

**Issue by Shazbot89** [dboissier/mongo4idea#207]
After getting a successful test connection, attempting to open the cluster from the panel runs into an exception:

> Document does not contain key ns
org.bson.BsonInvalidOperationException: Document does not contain key ns
	at org.bson.BsonDocument.throwIfKeyAbsent(BsonDocument.java:799)
	at org.bson.BsonDocument.getString(BsonDocument.java:220)
	at com.mongodb.operation.OperationHelper.cursorDocumentToQueryResult(OperationHelper.java:146)
	at com.mongodb.operation.OperationHelper.getMoreCursorDocumentToQueryResult(OperationHelper.java:140)
	at com.mongodb.operation.QueryBatchCursor.initFromCommandResult(QueryBatchCursor.java:252)
	at com.mongodb.operation.QueryBatchCursor.getMore(QueryBatchCursor.java:209)
	at com.mongodb.operation.QueryBatchCursor.hasNext(QueryBatchCursor.java:103)
	at com.mongodb.MongoBatchCursorAdapter.hasNext(MongoBatchCursorAdapter.java:46)
	at com.mongodb.MongoMappingCursor.hasNext(MongoMappingCursor.java:39)
	at org.codinjutsu.tools.mongo.logic.MongoManager.createMongoDatabaseAndItsCollections(MongoManager.java:150)
	at org.codinjutsu.tools.mongo.logic.MongoManager.access$000(MongoManager.java:38)
	at org.codinjutsu.tools.mongo.logic.MongoManager$2.run(MongoManager.java:99)
	at org.codinjutsu.tools.mongo.logic.MongoManager$2.run(MongoManager.java:87)
	at org.codinjutsu.tools.mongo.logic.MongoManager.execute(MongoManager.java:168)
	at org.codinjutsu.tools.mongo.logic.MongoManager.executeTask(MongoManager.java:158)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadDatabaseCollections(MongoManager.java:106)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadServer(MongoManager.java:79)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.run(MongoExplorerPanel.java:160)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Versions**
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

Plugin:
0.10.2016

**Comment by TristanDoherty** [comment]
I am getting the same error

`Document does not contain key ns
org.bson.BsonInvalidOperationException: Document does not contain key ns
	at org.bson.BsonDocument.throwIfKeyAbsent(BsonDocument.java:799)
	at org.bson.BsonDocument.getString(BsonDocument.java:220)
	at com.mongodb.operation.OperationHelper.cursorDocumentToQueryResult(OperationHelper.java:146)
	at com.mongodb.operation.OperationHelper.getMoreCursorDocumentToQueryResult(OperationHelper.java:140)
	at com.mongodb.operation.QueryBatchCursor.initFromCommandResult(QueryBatchCursor.java:252)
	at com.mongodb.operation.QueryBatchCursor.getMore(QueryBatchCursor.java:209)
	at com.mongodb.operation.QueryBatchCursor.hasNext(QueryBatchCursor.java:103)
	at com.mongodb.MongoBatchCursorAdapter.hasNext(MongoBatchCursorAdapter.java:46)
	at com.mongodb.MongoMappingCursor.hasNext(MongoMappingCursor.java:39)
	at org.codinjutsu.tools.mongo.logic.MongoManager.createMongoDatabaseAndItsCollections(MongoManager.java:150)
	at org.codinjutsu.tools.mongo.logic.MongoManager.access$000(MongoManager.java:38)
	at org.codinjutsu.tools.mongo.logic.MongoManager$2.run(MongoManager.java:99)
	at org.codinjutsu.tools.mongo.logic.MongoManager$2.run(MongoManager.java:87)
	at org.codinjutsu.tools.mongo.logic.MongoManager.execute(MongoManager.java:168)
	at org.codinjutsu.tools.mongo.logic.MongoManager.executeTask(MongoManager.java:158)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadDatabaseCollections(MongoManager.java:106)
	at org.codinjutsu.tools.mongo.logic.MongoManager.loadServer(MongoManager.java:79)
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$3.run(MongoExplorerPanel.java:160)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Versions
PyCharm 2017.3.3 (Community Edition)
Build #PC-173.4301.16, built on January 11, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin:
0.10.2016

**Comment by dboissier** [comment]
Did you tried to list all your mongo server addresses in the server url field. For instance `localhost:27017,localhost:27018,...`

**Comment by Shazbot89** [comment]
I am working back through the steps now to reproduce and give better information, but it was a stock cluster on [MongoDB Atlas](https://www.mongodb.com/cloud/atlas).

**Comment by dboissier** [comment]
Hi,

I just read that MongoDB Atlas use a different protocol name `mongo+srv` (see this [documentation page](https://docs.atlas.mongodb.com/driver-connection/#java-driver-example).

I will look at it.
