### ISSUE TITLE
mongo plugin crashing after updating intellij

### ISSUE THREAD

**Issue by villesau** [dboissier/mongo4idea#89]
here is the stacktrace:

null
java.lang.NullPointerException
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$2.run(MongoExplorerPanel.java:124)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

java.lang.NullPointerException
	at org.codinjutsu.tools.mongo.view.MongoExplorerPanel$2.run(MongoExplorerPanel.java:124)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by jorgeartware** [comment]
Same issue here:
https://gist.github.com/jorgeartware/396a8cad56d8dd8f8861

It crashed during webstorm restart.
Not sure if it is relevant but I had just installed pyCharm community edition while I had webstorm open at the same time and then closed pycharm and restarted webstorm, it was about to finish loading just before this error showed up.
Could it be an encapsulation error/conflict of the intellyJ api maybe?

**Comment by dboissier** [comment]
Hi,

Thanks for this stacktrace. The root cause seems to be the same than the stacktrace mentioned at the top of this thread.
Could you please remove the plugin, reinstall it from Webstorm and tell me if the bug still occurs?

Thanks.

**Comment by dboissier** [comment]
Hi,

I uploaded a [snapshot](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) version tested on Webstorm 9. It should work on Idea 14 too.

Please tell me if it works on your IDE.

David

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository
